"""soft_delete

Revision ID: 0b56265ed0c4
Revises: 9609fa391edc
Create Date: 2025-11-10 09:48:58.773202

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Import sqlmodel for SQLModel-specific types (AutoString, etc.)

# revision identifiers, used by Alembic.
revision: str = '0b56265ed0c4'
down_revision: str | Sequence[str] | None = '9609fa391edc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k_deployment_env', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_deployment_env', 'deleted')
    op.add_column('k_doc', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_doc', 'deleted')
    op.add_column('k_feature', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_feature', 'deleted')
    op.add_column('k_feature_doc', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_fido2_credential', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_fido2_credential', 'deleted')
    op.add_column('k_organization', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_organization', 'deleted')
    op.add_column('k_organization_principal', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_principal', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_principal', 'deleted')
    op.add_column('k_project', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_project', 'deleted')
    op.add_column('k_project_feature', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_project_team', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_sprint', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_sprint', 'deleted')
    op.add_column('k_sprint_task', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_sprint_team', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_task', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_task', 'deleted')
    op.add_column('k_task_deployment_env', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_task_feature', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_task_owner', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_task_reviewer', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_team', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('k_team', 'deleted')
    op.add_column('k_team_member', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('k_team_reviewer', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k_team_reviewer', 'deleted_at')
    op.drop_column('k_team_member', 'deleted_at')
    op.add_column('k_team', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_team', 'deleted_at')
    op.drop_column('k_task_reviewer', 'deleted_at')
    op.drop_column('k_task_owner', 'deleted_at')
    op.drop_column('k_task_feature', 'deleted_at')
    op.drop_column('k_task_deployment_env', 'deleted_at')
    op.add_column('k_task', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_task', 'deleted_at')
    op.drop_column('k_sprint_team', 'deleted_at')
    op.drop_column('k_sprint_task', 'deleted_at')
    op.add_column('k_sprint', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_sprint', 'deleted_at')
    op.drop_column('k_project_team', 'deleted_at')
    op.drop_column('k_project_feature', 'deleted_at')
    op.add_column('k_project', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_project', 'deleted_at')
    op.add_column('k_principal', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_principal', 'deleted_at')
    op.drop_column('k_organization_principal', 'deleted_at')
    op.add_column('k_organization', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_organization', 'deleted_at')
    op.add_column('k_fido2_credential', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_fido2_credential', 'deleted_at')
    op.drop_column('k_feature_doc', 'deleted_at')
    op.add_column('k_feature', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_feature', 'deleted_at')
    op.add_column('k_doc', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_doc', 'deleted_at')
    op.add_column('k_deployment_env', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('k_deployment_env', 'deleted_at')
    # ### end Alembic commands ###
