"""add_doc_yupdate_table

Revision ID: 353556ff2f4b
Revises: 9609fa391edc
Create Date: 2025-12-08 18:04:12.474856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import sqlmodel for SQLModel-specific types (AutoString, etc.)
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '353556ff2f4b'
down_revision: Union[str, Sequence[str], None] = '9609fa391edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k_doc_yupdate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('yupdate', sa.LargeBinary(), nullable=False),
    sa.Column('yupdate_meta', sa.LargeBinary(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['k_doc.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_yupdate_doc_timestamp', 'k_doc_yupdate', ['doc_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_k_doc_yupdate_doc_id'), 'k_doc_yupdate', ['doc_id'], unique=False)
    op.create_index(op.f('ix_k_doc_yupdate_org_id'), 'k_doc_yupdate', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_k_doc_yupdate_org_id'), table_name='k_doc_yupdate')
    op.drop_index(op.f('ix_k_doc_yupdate_doc_id'), table_name='k_doc_yupdate')
    op.drop_index('idx_doc_yupdate_doc_timestamp', table_name='k_doc_yupdate')
    op.drop_table('k_doc_yupdate')
    # ### end Alembic commands ###
