"""initial_schema

Revision ID: b8d7cdbf5c73
Revises: 
Create Date: 2025-11-09 17:55:23.629075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import sqlmodel for SQLModel-specific types (AutoString, etc.)
import sqlmodel

# Helper function to create enum types safely (check if they exist first)
def create_enum_if_not_exists(enum_type):
    """Create a PostgreSQL enum type only if it doesn't already exist."""
    from sqlalchemy.dialects import postgresql
    if isinstance(enum_type, postgresql.ENUM):
        # Check if enum type exists
        conn = op.get_bind()
        enum_name = enum_type.name
        result = conn.execute(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = :name)"
            ),
            {"name": enum_name}
        )
        exists = result.scalar()
        if not exists:
            enum_type.create(conn, checkfirst=False)
    elif hasattr(enum_type, 'create'):
        # For other enum types, use checkfirst
        conn = op.get_bind()
        enum_type.create(conn, checkfirst=True)

# revision identifiers, used by Alembic.
revision: str = 'b8d7cdbf5c73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k_organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('name')
    )
    op.create_table('k_principal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('primary_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('primary_email_verified', sa.Boolean(), nullable=False),
    sa.Column('primary_phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('primary_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('human', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('time_zone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_prefix', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_suffix', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('default_locale', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('system_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'username')
    )
    op.create_table('k_deployment_env',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name')
    )
    op.create_index(op.f('ix_k_deployment_env_org_id'), 'k_deployment_env', ['org_id'], unique=False)
    op.create_table('k_doc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name')
    )
    op.create_index(op.f('ix_k_doc_org_id'), 'k_doc', ['org_id'], unique=False)
    op.create_table('k_feature',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('parent', sa.Uuid(), nullable=True),
    sa.Column('parent_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feature_type', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('guestimate', sa.Float(), nullable=True),
    sa.Column('derived_guestimate', sa.Float(), nullable=True),
    sa.Column('review_result', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['k_feature.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name')
    )
    op.create_index(op.f('ix_k_feature_org_id'), 'k_feature', ['org_id'], unique=False)
    op.create_index(op.f('ix_k_feature_parent'), 'k_feature', ['parent'], unique=False)
    op.create_table('k_fido2_credential',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('aaguid', sa.LargeBinary(), nullable=False),
    sa.Column('transports', sa.JSON(), nullable=False),
    sa.Column('is_discoverable', sa.Boolean(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['k_principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k_fido2_credential_credential_id'), 'k_fido2_credential', ['credential_id'], unique=True)
    op.create_index(op.f('ix_k_fido2_credential_principal_id'), 'k_fido2_credential', ['principal_id'], unique=False)
    op.create_table('k_organization_principal',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['principal_id'], ['k_principal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'principal_id')
    )
    op.create_table('k_principal_identity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('public_key', sa.LargeBinary(), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['k_principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k_principal_identity_principal_id'), 'k_principal_identity', ['principal_id'], unique=False)
    op.create_table('k_project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name')
    )
    op.create_index(op.f('ix_k_project_org_id'), 'k_project', ['org_id'], unique=False)
    op.create_table('k_sprint',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('BACKLOG', 'ACTIVE', 'DONE', name='sprintstatus'), nullable=False),
    sa.Column('end_ts', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k_sprint_org_id'), 'k_sprint', ['org_id'], unique=False)
    op.create_table('k_team',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name')
    )
    op.create_index(op.f('ix_k_team_org_id'), 'k_team', ['org_id'], unique=False)
    op.create_table('k_feature_doc',
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['k_doc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['k_feature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'doc_id')
    )
    op.create_index(op.f('ix_k_feature_doc_org_id'), 'k_feature_doc', ['org_id'], unique=False)
    op.create_table('k_project_feature',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['k_feature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['k_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'feature_id')
    )
    op.create_index(op.f('ix_k_project_feature_org_id'), 'k_project_feature', ['org_id'], unique=False)
    op.create_table('k_project_team',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['k_project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['k_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'team_id')
    )
    op.create_index(op.f('ix_k_project_team_org_id'), 'k_project_team', ['org_id'], unique=False)
    op.create_table('k_sprint_team',
    sa.Column('sprint_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['k_sprint.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['k_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sprint_id', 'team_id')
    )
    op.create_index(op.f('ix_k_sprint_team_org_id'), 'k_sprint_team', ['org_id'], unique=False)
    op.create_table('k_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('guestimate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('review_result', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['k_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k_task_org_id'), 'k_task', ['org_id'], unique=False)
    op.create_index(op.f('ix_k_task_team_id'), 'k_task', ['team_id'], unique=False)
    op.create_table('k_team_member',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['k_principal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['k_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'principal_id')
    )
    op.create_index(op.f('ix_k_team_member_org_id'), 'k_team_member', ['org_id'], unique=False)
    op.create_table('k_team_reviewer',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['k_principal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['k_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'principal_id')
    )
    op.create_index(op.f('ix_k_team_reviewer_org_id'), 'k_team_reviewer', ['org_id'], unique=False)
    op.create_table('k_sprint_task',
    sa.Column('sprint_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['k_sprint.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['k_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sprint_id', 'task_id')
    )
    op.create_index(op.f('ix_k_sprint_task_org_id'), 'k_sprint_task', ['org_id'], unique=False)
    op.create_table('k_task_deployment_env',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_env_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_env_id'], ['k_deployment_env.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['k_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'deployment_env_id')
    )
    op.create_index(op.f('ix_k_task_deployment_env_org_id'), 'k_task_deployment_env', ['org_id'], unique=False)
    op.create_table('k_task_feature',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['k_feature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['k_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'feature_id')
    )
    op.create_index(op.f('ix_k_task_feature_org_id'), 'k_task_feature', ['org_id'], unique=False)
    op.create_table('k_task_owner',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['k_principal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['k_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'principal_id')
    )
    op.create_index(op.f('ix_k_task_owner_org_id'), 'k_task_owner', ['org_id'], unique=False)
    op.create_table('k_task_reviewer',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['k_organization.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['k_principal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['k_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'principal_id')
    )
    op.create_index(op.f('ix_k_task_reviewer_org_id'), 'k_task_reviewer', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_k_task_reviewer_org_id'), table_name='k_task_reviewer')
    op.drop_table('k_task_reviewer')
    op.drop_index(op.f('ix_k_task_owner_org_id'), table_name='k_task_owner')
    op.drop_table('k_task_owner')
    op.drop_index(op.f('ix_k_task_feature_org_id'), table_name='k_task_feature')
    op.drop_table('k_task_feature')
    op.drop_index(op.f('ix_k_task_deployment_env_org_id'), table_name='k_task_deployment_env')
    op.drop_table('k_task_deployment_env')
    op.drop_index(op.f('ix_k_sprint_task_org_id'), table_name='k_sprint_task')
    op.drop_table('k_sprint_task')
    op.drop_index(op.f('ix_k_team_reviewer_org_id'), table_name='k_team_reviewer')
    op.drop_table('k_team_reviewer')
    op.drop_index(op.f('ix_k_team_member_org_id'), table_name='k_team_member')
    op.drop_table('k_team_member')
    op.drop_index(op.f('ix_k_task_team_id'), table_name='k_task')
    op.drop_index(op.f('ix_k_task_org_id'), table_name='k_task')
    op.drop_table('k_task')
    op.drop_index(op.f('ix_k_sprint_team_org_id'), table_name='k_sprint_team')
    op.drop_table('k_sprint_team')
    op.drop_index(op.f('ix_k_project_team_org_id'), table_name='k_project_team')
    op.drop_table('k_project_team')
    op.drop_index(op.f('ix_k_project_feature_org_id'), table_name='k_project_feature')
    op.drop_table('k_project_feature')
    op.drop_index(op.f('ix_k_feature_doc_org_id'), table_name='k_feature_doc')
    op.drop_table('k_feature_doc')
    op.drop_index(op.f('ix_k_team_org_id'), table_name='k_team')
    op.drop_table('k_team')
    op.drop_index(op.f('ix_k_sprint_org_id'), table_name='k_sprint')
    op.drop_table('k_sprint')
    op.drop_index(op.f('ix_k_project_org_id'), table_name='k_project')
    op.drop_table('k_project')
    op.drop_index(op.f('ix_k_principal_identity_principal_id'), table_name='k_principal_identity')
    op.drop_table('k_principal_identity')
    op.drop_table('k_organization_principal')
    op.drop_index(op.f('ix_k_fido2_credential_principal_id'), table_name='k_fido2_credential')
    op.drop_index(op.f('ix_k_fido2_credential_credential_id'), table_name='k_fido2_credential')
    op.drop_table('k_fido2_credential')
    op.drop_index(op.f('ix_k_feature_parent'), table_name='k_feature')
    op.drop_index(op.f('ix_k_feature_org_id'), table_name='k_feature')
    op.drop_table('k_feature')
    op.drop_index(op.f('ix_k_doc_org_id'), table_name='k_doc')
    op.drop_table('k_doc')
    op.drop_index(op.f('ix_k_deployment_env_org_id'), table_name='k_deployment_env')
    op.drop_table('k_deployment_env')
    op.drop_table('k_principal')
    op.drop_table('k_organization')
    # ### end Alembic commands ###
